Upgrade sdk to use vault 31 keystore 5.4.1
Meeco/js-sdk pull request #170
Opened 2021-05-20 07:05 UTC by spazworm

big merge including the 

upgrade of the vault-api-sdk
upgrade of the keystore-api-sdk
eddy's delegation changes
josh's file package changes

plus adding a few other little helper bits like, 

making sure you're using the right version of node for this repo

The biggest dick around is probably the Enum changes, those may or may not be a real PITA

2021-05-20 07:06 UTC, spazworm commented
I'll do some more upgrades of other non meeco packages soon but this PR is big enough as it is

2021-05-21 01:02 UTC, zbarbuto requested changes

2021-05-21 01:02 UTC, zbarbuto commented on scripts/check-node-and-npm-versions.ts
> +exec('node -v', (error, stdout: string, stderr) => {
Not needed - `process.version` variable contains the node version.

2021-05-21 01:20 UTC, zbarbuto commented on packages/cli/src/commands/organization-services/create.ts
> +          publicKey: result.publicKey.key,
Ah I see - this is an actual inconsistent typing issue. Maybe update `.key` on public key to be `.pem` and deprecate `.key`. They really should be the same getters.

2021-05-21 01:54 UTC, zbarbuto approved these changes

2021-05-21 02:37 UTC, merged