Update connection/invitation service to add pagination response
Meeco/js-sdk pull request #271
Opened 2023-11-27 04:36 UTC by gongte1937

Add pagination response for connection service and invitation service.

2023-11-27 05:12 UTC, vijayshiyani requested changes

2023-11-27 05:12 UTC, vijayshiyani commented on packages/sdk/test/services/connection-service.test.ts
> +        for (const connection of connections.connections) {
@gongte1937 could you please check for the `meta` and `next_page_after` properties?

2023-11-27 05:12 UTC, vijayshiyani commented on packages/sdk/src/services/invitation-service.ts
> +  ): Promise<InvitationsResponse> {
@gongte1937 could you please also update invitation list tests
https://github.com/Meeco/js-sdk/blob/develop/packages/sdk/test/services/invitation-service.test.ts#L41

2023-11-27 08:04 UTC, linasi commented on packages/sdk/test/services/invitation-service.test.ts
> +      .it('returns a list of invitations',);
@gongte1937 is there a reason for this comma here?

2023-11-27 08:07 UTC, linasi commented on packages/sdk/package.json
> +  "version": "5.0.0",
This change doesn't bring any major breaking changes. I suggest `4.21.0` as a new version number.

2023-11-28 00:27 UTC, gongte1937 commented on packages/sdk/test/services/invitation-service.test.ts
> +      .it('returns a list of invitations',);
@linasi  Yes, I was planing to create a function here but forgot to update, I have already updated the test here, now should be good.

2023-11-28 00:28 UTC, gongte1937 commented on packages/sdk/src/services/invitation-service.ts
> +  ): Promise<InvitationsResponse> {
already updated

2023-11-28 05:37 UTC, vijayshiyani approved these changes

2023-11-28 05:40 UTC, merged